version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: java-mongo-app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    command: ["java", "-jar", "app.jar"]

volumes:
  mongo-data:
