services:
  maventest:
    container_name: "maventest-1"
    hostname: "maventest-1"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - logstash
    networks:
      - elk
  logstash:
    image: ./logstash/
    container_name: logstash
    ports:
      - "5044:5044"
    networks:
      - elk


  elasticsearch:
    build: ./elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk


  kibana:
    build: ./kibana/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge