services:
  maventest:
    container_name: "maventest-1"
    hostname: "maventest-1"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - logstash
    networks:
      - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elk

networks:
  elk:
    driver: bridge